### ISSUE TITLE
documentation for minimize function

### ISSUE THREAD

**Issue by prasadkumar0590** [scikit-quant/scikit-quant#17]
For the minimize function what are all the parameters we need to pass do you have any documentation for parameters with description and also we can pass kwargs for last parameter. What are key value pairs we can pass in kwargs. If you have any documentation with some examples it would be a great help for us.

**Comment by wlav** [comment]
For SQNomad, right? So, the NOMAD manual: https://www.gerad.ca/nomad/

Any option that is not a common one (objective, start point, bounds, ... ) will be kwargs one. E.g. `SEED=12345`.

I haven't worked through the whole manual yet, so there may be corners that do not work at this point. And the port to Windows is literally of last week.

**Comment by prasadkumar0590** [comment]
what exactly first parameter(objective_function) does. I checked in user manual as well. did not get it. Can you please elaborate it.

**Comment by wlav** [comment]
The `objective_function` is the function to minimize. It takes the current point as a `numpy` array. Here's an example: https://scikit-quant.readthedocs.io/en/latest/starting.html

**Comment by prasadkumar0590** [comment]
I have couple of questions

1. What is return type of objective_function
2. **Any option that is not a common one (objective, start point, bounds, ... ) will be kwargs one. E.g. SEED=12345.** Can you please provide some useful parameters as I have seen this in NOMAD manual, parameters names are different.
3. what is the range of start point
4. what is the range of bounds

**Comment by wlav** [comment]
1. a Python float
2. what is useful depends on your problem: read the NOMAD manual for a detailed description
3. whatever you choose, as long as it is in bounds
4. whatever you choose as relevant for your problem, but obviously, smaller is better

Please, NOMAD is a specialized optimizer for noisy black-box objectives. You will have to put in the effort yourself to get something out of it as it all depends on the specifics of the problem at hand. Otherwise, you're much better off taking one of the SciPy optimizers even if your problem is noisy (just pick one of the trust region methods in that case).

**Comment by prasadkumar0590** [comment]
We have implemented SLSQP optimization using pymoo and scipy. same way we want to implement nomad. but we are not sure which extra parameters need to pass it to minimize function. if you have any idea please let us know. It is a great help for us.

**Comment by prasadkumar0590** [comment]
Thank you for your help. It seems there are some parameter name differences.


your   python library | Nomad manual
-- | --
budget | MAX_BB_EVAL



This is one of the example I think there are many like this. If you can give us some kind of documentation for python minimize function parameters it would be great help for us.

**Comment by wlav** [comment]
Not following ...

With scikit-quant, I'm trying to have a bit of a consistent interface across a series of optimizers to allow them to be somewhat interchangeable. So far that's the objective_function, initial, bounds, and budget. This list will grow, but either which way, they are documented in the link I gave you above (https://scikit-quant.readthedocs.io/en/latest/starting.html). If you're not interested in that, just use upstream NOMAD directly (https://github.com/bbopt/nomad).

Now, in the case of NOMAD, those common parameters are mapped to the underlying optimizer's parameters, yes, so initial to `X0`, bounds to `LOWER_BOUND, UPPER_BOUND`, and budget to `MAX_BB_EVAL`. The objective function is its own can of worms, as it needs to map from Python to C++ which limits some functionality (e.g. due to the GIL), but it's also one of the most basic pieces, so I don't see what's unclear about it. And yes, true as is, `MAX_BB_EVAL` can not be overwritten again through the keyword arguments (unless you use the lower level `libsqnomad.minimize` function), but everything else is fair game, including initial and bounds (although for the life of me, I don't see why you'd want to do that), so where does this idea come from that there are "many like this"?

Look, if something is not working and you send a reproducer, I can help/fix. If you explain the specific use case you're after, I can (perhaps) offer advice. But vague, non-specific questions like "give us some kind of documentation for python minimize function parameters" are unanswerable, so I have no idea what you're expecting from me here.

**Comment by prasadkumar0590** [comment]
Thank you wlav. I appreciate your help. I mean to say there are almost above 50 parameters in nomad manual. is scikit-quant library
supports all the parameters from nomad manual.

**Comment by wlav** [comment]
Yes, as said: through keyword args.
